name: unittest
version: 0.12.0-beta.0
author: Dart Team <misc@dartlang.org>
description: A library for writing dart unit tests.
homepage: https://github.com/dart-lang/unittest
environment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  analyzer: '>=0.23.0 <0.26.0'
  args: '>=0.12.1 <0.14.0'
  http_parser: '^0.0.2'
  pool: '^1.0.0'
  shelf: '^0.5.3'
  shelf_static: '^0.2.0'
  shelf_web_socket: '^0.0.1'
  source_span: '^1.0.0'
  stack_trace: '^1.2.0'

  # Use a tight version constraint to ensure that a constraint on unittest
  # properly constraints all features it provides.
  matcher: '^0.12.0-alpha.0'
dev_dependencies:
  fake_async: '^0.1.2'
